apiVersion: apps/v1
kind: Deployment
metadata:
  name: jjhjj
spec:
  selector:
    matchLabels:
      app: Muhammad
  replicas: 3
  template:
    metadata:
      name: my-first-pod
      labels:
        app: Muhammad
    spec:
      containers:
        - image: nginx:alpine
          name: nginx-container
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "100Mi"  
    