on: 
  push:
    branches:
       - master



jobs:
  build: 
     runs-on: ubuntu-t-latest 


     steps:
       - uses: actions/checkout@v3
        

     
 
       - name: 'login to dockerhub'
         run: docker login --username habiba2002 --password dckr_pat_zIOTPwb2du6pMbkHWyObDt_Xo54

